### ISSUE TITLE
problem in RTL Directionality

### ISSUE THREAD

**Issue by resfandiari** [taljacobson/flutter_search_bar_transition#1]
there is a problem when setting RTL direction to the app

```dart
 Directionality(
          textDirection: TextDirection.rtl,
          child: MyHomePage(title: 'Flutter Demo Home Page')),
    )
```
![image](https://user-images.githubusercontent.com/47494761/92587753-4d65c280-f2ad-11ea-9235-791d0d44bfa7.png)

**Comment by taljacobson** [comment]
Fixed the issue with 0.2.1, reveal clipper was not hiding the appbar correctly. 

Only thing is that I tried to make the reveal grow from the opposite side, where the search icon is, but to no avail.
